# Generated by Django 5.0.4 on 2025-04-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltasklog',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='TaskLog',
        ),
        migrations.DeleteModel(
            name='HistoricalTaskLog',
        ),
    ]
