# Generated by Django 5.0.4 on 2025-04-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltasklog',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical сelery', 'verbose_name_plural': 'historical сelery'},
        ),
        migrations.AlterModelOptions(
            name='tasklog',
            options={'ordering': ['-created_at'], 'verbose_name': 'сelery', 'verbose_name_plural': 'сelery'},
        ),
    ]
