name: CI for all branches

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t boilerplate .

      - name: Run pytest inside Docker
        run: |
          docker run --rm \
            -e DEBUG=True \
            -e SECRET_KEY=secret \
            -e POSTGRES_USER=django_user \
            -e POSTGRES_PASSWORD=django_password \
            -e POSTGRES_DB=django_db \
            -e POSTGRES_HOST=db \
            -e POSTGRES_PORT=5432 \
            --link db \
            boilerplate pytest --maxfail=1 --disable-warnings -q
