name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5433:5433
        env_file:
          - .env
        options: --health-cmd="pg_isready -U django_user" --health-timeout=30s --health-retries=3

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for DB to be ready
        run: |
          until docker exec $(docker ps -qf "name=ci_db") pg_isready -U django_user; do
            echo "Waiting for database to be ready..."
            sleep 2
          done

      - name: Run migrations
        run: |
          docker-compose exec web python manage.py migrate

      - name: Run tests
        run: |
          docker-compose exec web pytest --maxfail=1 --disable-warnings -q

      - name: Tear down Docker Compose
        run: |
          docker-compose down
