name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run migrations
        run: |
          docker-compose exec web python manage.py migrate

      - name: Run tests
        run: |
          docker-compose exec web pytest --maxfail=1 --disable-warnings -q

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose down
